# Generated by Django 2.2.5 on 2019-10-16 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criterios', '0002_criterioboleano_justifiacionbajas'),
        ('departamento', '0003_docente'),
        ('frecuencia', '0001_initial'),
        ('indicadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleIndicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docIndicador', models.FileField(default='Doc/None/No-doc.pdf', upload_to='Doc/')),
                ('bajas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criterios.JustifiacionBajas')),
                ('criterioBoleano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criterios.CriterioBoleano')),
                ('criterioNumerico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criterios.CriterioNumerico')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departamento.Departamento')),
                ('frecuencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frecuencia.Frecuencia')),
                ('indicador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicadores.Indicador')),
            ],
        ),
    ]
