# Generated by Django 2.2.5 on 2019-10-30 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePermiso', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permisop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rol.Permiso')),
                ('rolp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rol.Rol')),
            ],
        ),
    ]
