# Generated by Django 2.2.5 on 2019-10-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioBoleano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCriterioB', models.CharField(blank=True, max_length=100)),
                ('SiNo', models.BooleanField(default=False)),
                ('docCriterioB', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JustifiacionBajas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreBaja', models.CharField(max_length=25)),
                ('SiNo', models.BooleanField(default=False)),
            ],
        ),
    ]
