# Generated by Django 2.2.5 on 2019-10-15 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMes', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Frecuencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreFrecuencia', models.CharField(blank=True, max_length=50)),
                ('mesFrecuencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frecuencia.Mes')),
            ],
        ),
    ]
